src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository", repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"pseudo"}, message="There is already an account with this pseudo")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="date")
     */
    private $date_inscription;

    /**
     * @ORM\Column(type="string", length=180)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $derniere_connexion;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_parties = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_victoires = 0;

    /**
     * @ORM\OneToMany(targetEntity=Game::class, mappedBy="user1")
     */
    private $games1;

    /**
     * @ORM\OneToMany(targetEntity=Game::class, mappedBy="user2")
     */
    private $games2;

    /**
     * @ORM\Column(type="string")
     */
    private $roles = 'ROLE_USER';

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $presentation;

    public function __construct()
    {
        $this->games1 = new ArrayCollection();
        $this->games2 = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getDateInscription(): ?\DateTimeInterface
    {
        return $this->date_inscription;
    }

    public function setDateInscription(\DateTimeInterface $date_inscription): self
    {
        $this->date_inscription = $date_inscription;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getDerniereConnexion(): ?\DateTimeInterface
    {
        return $this->derniere_connexion;
    }

    public function setDerniereConnexion(?\DateTimeInterface $derniere_connexion): self
    {
        $this->derniere_connexion = $derniere_connexion;

        return $this;
    }

    public function getNbParties(): ?int
    {
        return $this->nb_parties;
    }

    public function setNbParties(int $nb_parties): self
    {
        $this->nb_parties = $nb_parties;

        return $this;
    }

    public function getNbVictoires(): ?int
    {
        return $this->nb_victoires;
    }

    public function setNbVictoires(int $nb_victoires): self
    {
        $this->nb_victoires = $nb_victoires;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames1(): Collection
    {
        return $this->games1;
    }

    public function addGames1(Game $games1): self
    {
        if (!$this->games1->contains($games1)) {
            $this->games1[] = $games1;
            $games1->setUser1($this);
        }

        return $this;
    }

    public function removeGames1(Game $games1): self
    {
        if ($this->games1->removeElement($games1)) {
            // set the owning side to null (unless already changed)
            if ($games1->getUser1() === $this) {
                $games1->setUser1(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames2(): Collection
    {
        return $this->games2;
    }

    public function addGames2(Game $games2): self
    {
        if (!$this->games2->contains($games2)) {
            $this->games2[] = $games2;
            $games2->setUser2($this);
        }

        return $this;
    }

    public function removeGames2(Game $games2): self
    {
        if ($this->games2->removeElement($games2)) {
            // set the owning side to null (unless already changed)
            if ($games2->getUser2() === $this) {
                $games2->setUser2(null);
            }
        }

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles[] = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(?string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Security;

class ProfilController extends AbstractController
{


    /**
     * @Route("/profil", name="profil")
     */
    public function index(UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        return $this->render('profil/index.html.twig', [
            'controller_name' => 'ProfilController',
            'user' => $user,
            'presEdit' => false,
            'dateInscription' => $user->getDateInscription()->format('d/m/Y')
        ]);
    }

    /**
     * @Route("/profil/edit", name="profil_presEdit")
     */
    public function presEdit(UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        return $this->render('profil/index.html.twig', [
            'controller_name' => 'ProfilController',
            'user' => $user,
            'presEdit' => 1,
            'dateInscription' => $user->getDateInscription()->format('d/m/Y')
        ]);
    }

    /**
     * @Route("/profil/presEditValid", name="profil_presEditValid")
     */
    public function presEditValid(EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        $pres = $_POST['presentation'];
        $user->setPresentation($pres);
        $entityManager->persist($user);
        $entityManager->flush();
        return $this->redirectToRoute('profil');
    }

    /**
     * @Route("/profil/edit/infos", name="profil_EditInfos")
     */
    public function editInfos(UserRepository $userRepository): Response
    {
        $user = $this->getUser();
        $mail = $_POST['mail'];
        $password = $_POST['password'];
        return $this->render('profil/edit_infos.html.twig',[
            'user' => $user,
            'mail' => $mail,
            'password' => $password,
            'error' => false
        ]);
    }

    private $passwordEncoder;
    /**
     * @Route("/profil/edit/infos_valid", name="profil_EditInfosValid")
     */
    public function editInfosValid(UserPasswordEncoderInterface $passwordEncoder, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {

        $user = $this->getUser();
        $mail = $_POST['mail'];
        $password = $_POST['password'];
        $password2 = $_POST['password2'];
        $password3 = $_POST['password3'];
        $this->passwordEncoder = $passwordEncoder;
        if($this->passwordEncoder->isPasswordValid($user, $password3)) {
            if ($password == $password2){
                $user->setMail($mail);
                $user->setPassword(
                    $passwordEncoder->encodePassword(
                        $user,
                        $password
                    )
                );
                $entityManager->persist($user);
                $entityManager->flush();
                return $this->redirectToRoute('profil');
            } else {
                $erreur = 'Les mots de passe ne correspond pas';
            }
        } else {
            $erreur = 'Mot de passe incorrect';
        }
        return $this->render('profil/edit_infos.html.twig',[
            'user' => $user,
            'mail' => $mail,
            'password' => $password,
            'error' => $erreur
        ]);
    }
}

templates/profil/edit_infos.html.twig
{% extends 'base.html.twig' %}

{% block title %}Senshi no Mishi | Modification du profil{% endblock %}
{% block stylesheets %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/styles/a/style.css') }}">
{% endblock %}
{% block body %}
    <div id="main_content">
        <header>
            <nav>
                <a href="{{ path('accueil') }}">Accueil</a>
                <a href="">Contact</a>
            </nav>
            <a href="{{ path('app_logout') }}">Déconnexion</a>
        </header>

    <section id="modification">

        <div id="profil" style="height: auto; width: auto;">
            <h1>Veuillez confirmer les informations enregistrées :</h1>
        <div id="modify" style="height: auto; width: 95%;">
            <form method="post" action="{{ path('profil_EditInfosValid') }}">
                {% if error %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endif %}
                <label >Mail :</label>
                <input type="email" name="mail" value="{{ mail }}">
                <label >Nouveau mot de passe :</label>
                <input type="password" name="password" value="{{ password }}">
                <label >Confirmez le nouveau mot de passe :</label>
                <input type="password" name="password2">
                <hr>
                <label >Mot de Passe actuel :</label>
                <input type="password" name="password3" required>
                <button id="valider" type="submit">VALIDER</button>
            </form>
        </div>
        </div>
    </section>
    </div>
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Senshi no Mishi | Profil de {{ user.pseudo }}{% endblock %}
{% block stylesheets %}
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/styles/a/style.css') }}">
{% endblock %}
{% block body %}
    <div id="main_content">
        <header>
            <nav>
                <a href="{{ path('accueil') }}">Accueil</a>
                <a href="{{ path('profil') }}">Profil</a>
            </nav>
            <a href="{{ path('app_logout') }}">Déconnexion</a>
        </header>

        <section id="modification">
            <div id="profil">
                <div id="img_profil">
                    <div id="img"></div>
                    <span></span>
                    <h1>{{ user.pseudo }}</h1>
                </div>
                <div id="info">
                    <h2>Mes informations personnelles</h2>
                    <p>Date d'inscription: {{ dateInscription }}</p>
                    <p><b>Présentation : </b>
                    {% if presEdit == 1 %}
                    <div id="modify">
                        <form method="post" action="{{ path('profil_presEditValid') }}">
                            <input id="modify_pres" type="text" height="50px" width="50px" name="presentation" value="{{ user.presentation }}">
                    </p>

                    </div>
                    <button id="valider" type="submit">VALIDER</button>
                </form>
                    {% elseif user.presentation %}
                            {{ user.presentation }}
                        </p>
                    <a href="{{ path('profil_presEdit') }}">MODIFIER</a>
                    {% else %}
                            <i>Vous n'avez pas encore rédigé votre présentation.</i>
                        </p>
                        <a href="{{ path('profil_presEdit') }}">MODIFIER</a>
                    {% endif %}
                </div>
                <div id="modify">
                    <form method="post" action="{{ path('profil_EditInfos') }}">
                        <label>Votre adresse email :</label>
                        <input type="email" name="mail" value="{{ user.mail }}">
                        <label>Votre mot de passe : </label>
                        <input type="password" name="password" id="inputPassword" class="form-control">
                        <button id="valider" class="valider_r" type="submit">Modifier mes informations</button>
                    </form>
                </div>
            </div>
        </section>

        <section id="game">
            <div id="left">
                <div id="stats">
                    <h2>Mes statistiques de jeu</h2>
                    <p>Nombre de parties jouées</p><p>{{ user.nbParties }}</p>
                    <hr>
                    <p>Parties gagnées</p><p>{{ user.nbVictoires }}</p>
                    <hr>
                    <p>Classement du joueur</p><p>16/340</p>
                </div>

                <div id="party">
                    <h2>Gestion des parties</h2>
                    <h3>Débuter une nouvelle partie</h3>
                    <img class="arrow" src="{{ asset('assets/imgs/arrow.png') }}">
                    <div id="start">
                        <p><img src="">Ouvrir une nouvelle table de jeu</p>
                        <p><img src="">Choisir une partie dans la liste des tables</p>
                        <p><img src="">Choisir un adversaire en ligne</p>
                        <p><img src="">Inviter un adversaire de la liste d'amis</p>
                        <p><img src="">Répondre à une invitation par mail</p>
                    </div>
                </div>
            </div>

            <div id="players">
                <div id="friends">
                    <h2>Mes amis</h2>
                    <p>Doneäl</p><span><span class="circle_connection"></span>En ligne</span>
                    <hr>
                    <p>Thirdullon</p><span><span class="circle_connection"></span>En ligne</span>
                    <hr>
                    <p>Classement du joueur</p>
                    <span>16/340</span>
                </div>
                <div id="users">
                    <h2>Utilisateurs en ligne</h2>
                    <p>User437</p>
                    <hr>
                    <p>Rififi</p>
                    <hr>
                    <p>JeanClaudeVD</p>
                    <hr>
                    <p>Valentin_10</p>
                </div>
                <div id="tables">
                    <h2>Tables ouvertes</h2>
                    <p>Imnor</p><a href=""><i>En attente</i></a>
                    <hr>
                    <p>Mûibeth</p><a href=""><b>Rejoindre</b></a>
                    <hr>
                    <p>Fartada</p>
                    <hr>
                    <p>Hartaerë</p>
                </div>
                <div id="my_party">
                    <h2>Mes parties</h2>
                    <a href="">Reprendre une partie en cours</a>
                    <a href="">Relancer une partie en envoyant un mail</a>
                    <a href="">Supprimer une partie en cours</a>
                </div>
            </div>
        </section>

        <footer>
            <nav>
                <a href="">Mentions légales</a>
                <p>-</p>
                <a href="">CGV</a>
                <p>-</p>
                <a href="">RGPD</a>
                <p>-</p>
                <a href="">CGU</a>
            </nav>
        </footer>
    </div>

{% endblock %}